CREATE TABLE AUDITLOGS (
    OBJECTID int,
    OBJECTTYPE varchar(2),
    ACTIONPERFORMED varchar(50),
    USERNAME varchar(32),
    IPADDRESS varchar(50),
    ACTIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    PARAMETERS varchar(255),
    COMMENTS varchar(500),
    AUDITLEVEL int
);

CREATE TABLE BOOKMARKS (
    ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(50),
    DOCUMENTID int,
    REVISIONID varchar(50),
    USERNAME varchar(32),
    CREATED timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

CREATE TABLE CHECKOUT
(
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) DEFAULT '1.0' NOT NULL,
    CLASSID int NOT NULL,
    USERNAME varchar(32),
    CHECKOUTPATH varchar(1000),
    CHECKOUTDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    COMMENTS varchar(1024)
);

CREATE TABLE DOCUMENTCLASSES (
    CLASSID int NOT NULL AUTO_INCREMENT,
    CLASSNAME varchar(64) NOT NULL,
    CLASSDESC varchar(128),
    INDEXID int,
    INDEXTABLENAME varchar(10),
    INDEXCOUNT int,
    DATATABLENAME varchar(16),
    REVISIONCTL varchar(1),
    MAXFILESIZE int DEFAULT 0 NOT NULL,
    DOCUMENTLIMIT int DEFAULT 0 NOT NULL,
    EXPIRYPERIOD int DEFAULT 0 NOT NULL,
    EXPIRYNOTIFICATIONPERIOD int DEFAULT 7 NOT NULL,
    CREATEDBY varchar(32),
    CREATED timestamp DEFAULT CURRENT_TIMESTAMP,
    ACTIVE varchar(1) DEFAULT 'Y',
    TOTALDOCUMENTS int DEFAULT 0,
    ACTIVEDOCUMENTS int DEFAULT 0,
	PRIMARY KEY(CLASSID)
);

CREATE TABLE DOCUMENTREVISIONS (
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) NOT NULL,
    SOFFSET int,
    LENGTH int
);

CREATE TABLE DOCUMENTS (
    DOCUMENTID int NOT NULL AUTO_INCREMENT,
    REVISIONID varchar(50) DEFAULT '1.0',
    CLASSID int,
    DOCUMENTTYPE varchar(8),
    STATUS varchar(8),
    CREATED timestamp DEFAULT CURRENT_TIMESTAMP,
    MODIFIED timestamp DEFAULT CURRENT_TIMESTAMP,
    EXPIRY timestamp,
    EXT varchar(16),
    HASNOTE int,
    LASTACCESS timestamp DEFAULT CURRENT_TIMESTAMP,
    ACCESSCOUNT int,
    CREATEDBY varchar(32),
    MODIFIEDBY varchar(32),
	PRIMARY KEY(DOCUMENTID)
);

CREATE TABLE I0000001 (
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) DEFAULT '1.0',
    CONTENT MEDIUMTEXT,
    IPODATE varchar(12),
    IPONUM varchar(20),
    ICUSTNAME varchar(30),
    IINVOICENUM varchar(20),
    IAMOUNT varchar(20)
);

CREATE TABLE I0000002 (
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) DEFAULT '1.0',
    CONTENT MEDIUMTEXT,
    IPONUM varchar(20),
    IINVOICENUM varchar(20),
    ISHIPDATE varchar(12),
    IPODATE varchar(12)
);

CREATE TABLE I0000003 (
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) DEFAULT '1.0',
    CONTENT MEDIUMTEXT,
    IPODATE varchar(12),
    ICUSTNO varchar(20),
    ICUSTNAME varchar(30),
    IPONUM varchar(20)
);

CREATE TABLE I0000004 (
    DOCUMENTID int NOT NULL,
    REVISIONID varchar(50) DEFAULT '1.0',
    CONTENT MEDIUMTEXT
);

CREATE TABLE INDEXES (
    INDEXID int NOT NULL,
    SEQ int NOT NULL,
    IDXCOLNAME varchar(50) NOT NULL,
    IDXDISPLAYNAME varchar(50) NOT NULL,
    IDXMAXLEN int,
    IDXTYPE varchar(1) DEFAULT 'S',
    DEFAULTFILTER varchar(255),
    DEFAULTVALUE varchar(255),
    MANDATORY varchar(1) DEFAULT 'N'
);

CREATE TABLE NOTES (
    ID int NOT NULL AUTO_INCREMENT,
    NOTEDATA varchar(2048) NOT NULL,
    DOCUMENTID int,
    USERNAME varchar(32),
    ACTIVE varchar(1) DEFAULT 'Y',
    NOTETYPE varchar(1) DEFAULT 'P',
    CREATED timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

CREATE TABLE PASSWORDHISTORY (
    USERID int NOT NULL,
    PASSWORD varchar(255),
    CHANGEDATE timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PERMISSIONS (
    ID int NOT NULL AUTO_INCREMENT,
    CLASSID int,
    USERID int,
    VALUE int DEFAULT 511,
	PRIMARY KEY(ID) 
);

CREATE TABLE REVISIONHISTORY (
    DOCUMENTID int,
    REVISIONID varchar(50),
    USERNAME varchar(32),
    USERACTION varchar(50),
    COMMENTS varchar(256),
    DATEOFACTION timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS (
    USERID int NOT NULL AUTO_INCREMENT,
    USERNAME varchar(32) NOT NULL,
    PASSWORD varchar(255),
    USERDESC varchar(64),
    USEREMAIL varchar(64),
    USERTYPE varchar(1),
    REALNAME varchar(64),
    IPADDRESS varchar(32),
    LASTLOGINDATE timestamp,
    HITLISTSIZE int DEFAULT 10,
    CHECKOUTPATH varchar(255) DEFAULT 'C:/TEMP',
    SHOWTHUMBNAIL varchar(8) DEFAULT 'TRUE',
    METACOLUMN int DEFAULT 511,
    ACTIVE varchar(1) DEFAULT 'Y',
    LOGGEDIN varchar(1) DEFAULT 'N',
    PROFILEPICTURE BLOB,
	PRIMARY KEY(USERID)
);

CREATE UNIQUE INDEX SQL180427125355320 ON USERS (USERNAME);

CREATE TABLE Z0000001 (
    DATAID int NOT NULL AUTO_INCREMENT,
    DATA BLOB,
	PRIMARY KEY(DATAID)
);

CREATE TABLE Z0000002 (
    DATAID int NOT NULL AUTO_INCREMENT,
    DATA BLOB,
	PRIMARY KEY(DATAID)
);

CREATE TABLE Z0000003 (
    DATAID int NOT NULL AUTO_INCREMENT,
    DATA BLOB,
	PRIMARY KEY(DATAID)
);

CREATE TABLE Z0000004 (
    DATAID int NOT NULL AUTO_INCREMENT,
    DATA BLOB,
	PRIMARY KEY(DATAID)
)